apiVersion: v1
data:
  FEATURE: stable and reliable feature
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: b117aca5-cb7e-4505-9bbf-1c1877a8df0e
  name: demo-feature-f995d97h79
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: b117aca5-cb7e-4505-9bbf-1c1877a8df0e
  name: flask-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: b117aca5-cb7e-4505-9bbf-1c1877a8df0e
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      env: prod
  template:
    metadata:
      labels:
        app: flask-app
        app.kubernetes.io/managed-by: skaffold
        env: prod
        skaffold.dev/run-id: b117aca5-cb7e-4505-9bbf-1c1877a8df0e
    spec:
      containers:
      - env:
        - name: FEATURE
          valueFrom:
            configMapKeyRef:
              key: FEATURE
              name: demo-feature-f995d97h79
        image: gcr.io/agmsb-k8s/flask-app:5b209b9@sha256:e6500a35804ef1de539e11d223a9f291eed41645f0df82803ad5cf8dea0f4d74
        imagePullPolicy: IfNotPresent
        name: flask-app
        ports:
        - containerPort: 5000
