apiVersion: v1
data:
  FEATURE: stable and reliable feature
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: f27596b1-0b6a-42d2-9c8d-eccda16e4e0a
  name: demo-feature-f995d97h79
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: f27596b1-0b6a-42d2-9c8d-eccda16e4e0a
  name: flask-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: f27596b1-0b6a-42d2-9c8d-eccda16e4e0a
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      env: prod
  template:
    metadata:
      labels:
        app: flask-app
        app.kubernetes.io/managed-by: skaffold
        env: prod
        skaffold.dev/run-id: f27596b1-0b6a-42d2-9c8d-eccda16e4e0a
    spec:
      containers:
      - env:
        - name: FEATURE
          valueFrom:
            configMapKeyRef:
              key: FEATURE
              name: demo-feature-f995d97h79
        image: gcr.io/agmsb-k8s/flask-app:c18aafd@sha256:5835e2a3e106ab6be1edac62a66f93a2053fbd3d25c6bab9146b094dc3767093
        imagePullPolicy: IfNotPresent
        name: flask-app
        ports:
        - containerPort: 5000
